void print_alphabet_x10(void);
void jack_bauer(void);
void times_table(void);
void print_alphabet(void);
int _putchar(char c);
int _abs(int);
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int print_last_digit(int);
int add(int,int);
